### ISSUE TITLE
Is not available on edge for this architecture

### ISSUE THREAD

**Issue by Laughlete** [ogra1/snapd-docker#7]
`error: snap "ubuntu-image" is not available on edge for this architecture`

With a pi 3 after running:
`sudo docker exec snappy snap install ubuntu-image --classic --edge`

**Comment by ogra1** [comment]
you should report this at https://bugs.launchpad.net/ubuntu-image/+filebug there isnt anything i could do here ... 

though note also that image building is a really bad example anyway given that ubuntu-image only uses binary snaps to build the image and the architecture is simply defined in the model assertion, there is nothing architecture bound in it so you can just run it on a PC to build arm images ...
